### ISSUE TITLE
Intel Arc GPU does not work under Linux

### ISSUE THREAD

**Issue by HubKing** [zackees/transcribe-anything#23]
I ran it, and it started downloading GB's of Nvidia-related packages and it printed

```
WARNING: NOT using GPU acceleration, using 10x slower CPU instead.
Using device cpu

```

I don't know much about A.I., but Vladmir's Automatic1111 works on Intel Arc, and it seemed to use PyTorch. So, there probably is a way to do this task too with an Intel Arc GPU. 

At least it should automatically detect the existing GPU and if it's not Nvidia, it should not download GB's unnecessary files. If detection is difficult, it could simply ask: "Do you have an Nvidia GPU?"

**Comment by Kreijstal** [comment]
I agree... it is wasteful to download nvidia code that you will never use

**Comment by zackees** [comment]
I don't have an Intel Arc so I can't test this. The detection to install the gpu version of whisper dependencies is fairly primitive. Unfortunately I can't test any fix for this. So it will have to be up to someone else to create a pull request.

**Comment by HubKing** [comment]
> I don't have an Intel Arc so I can't test this. The detection to install the gpu version of whisper dependencies is fairly primitive. Unfortunately I can't test any fix for this. So it will have to be up to someone else to create a pull request.

I can't write code, because I don't know how A.I. works, but I can test if something works or not.

**Comment by zackees** [comment]
I don't know how AI works either. But I am an expert in packaging up the dependencies to make it work.

You might be able to use my AI coding assistant to help you out:

`pip install advanced-aicode`

Then launch it in the repo:

`aicode`

I'll accept a PR to fix this and work around test failures.

**Comment by ikt** [comment]
Yeah a bit painful as an AMD user watching it download GB's of nvidia packages, hopefully someone can fix!

Thanks though this is great :)

**Comment by zackees** [comment]
I've painfully upgraded all of the dependencies to latest torch version.

See if this is now fixed. I can't test because my only linux is in a VM and doesn't have access to a gpu.

**Comment by HubKing** [comment]
I had reinstalled the OS, so I tried to reinstall it, but it does not seem to work. I created a VENV and then ran the install command, and then ran the sample command.

```
╰─$ pip install transcribe-anything
Collecting transcribe-anything
  Downloading transcribe_anything-3.0.0-py3-none-any.whl.metadata (19 kB)
Collecting static-ffmpeg>=2.7 (from transcribe-anything)
  Downloading static_ffmpeg-2.8-py3-none-any.whl.metadata (6.1 kB)
Collecting yt-dlp>=2025.1.15 (from transcribe-anything)
  Downloading yt_dlp-2025.2.19-py3-none-any.whl.metadata (171 kB)
Collecting appdirs>=1.4.4 (from transcribe-anything)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting disklru>=1.0.7 (from transcribe-anything)
  Downloading disklru-2.0.4-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting FileLock (from transcribe-anything)
  Downloading filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
Collecting webvtt-py==0.4.6 (from transcribe-anything)
  Downloading webvtt_py-0.4.6-py3-none-any.whl.metadata (2.7 kB)
Collecting uv-iso-env>=1.0.36 (from transcribe-anything)
  Downloading uv_iso_env-1.0.37-py3-none-any.whl.metadata (4.6 kB)
Collecting python-dotenv>=1.0.1 (from transcribe-anything)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting docopt (from webvtt-py==0.4.6->transcribe-anything)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests (from static-ffmpeg>=2.7->transcribe-anything)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting progress (from static-ffmpeg>=2.7->transcribe-anything)
  Downloading progress-1.6.tar.gz (7.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting twine>=6.0.1 (from uv-iso-env>=1.0.36->transcribe-anything)
  Downloading twine-6.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting uv>=0.5.22 (from uv-iso-env>=1.0.36->transcribe-anything)
  Downloading uv-0.6.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting readme-renderer>=35.0 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading readme_renderer-44.0-py3-none-any.whl.metadata (2.8 kB)
Collecting requests-toolbelt!=0.9.0,>=0.8.0 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting urllib3>=1.26.0 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting keyring>=15.1 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading keyring-25.6.0-py3-none-any.whl.metadata (20 kB)
Collecting rfc3986>=1.4.0 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading rfc3986-2.0.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting rich>=12.0.0 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting packaging>=24.0 (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting id (from twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading id-1.5.0-py3-none-any.whl.metadata (5.2 kB)
Collecting charset-normalizer<4,>=2 (from requests->static-ffmpeg>=2.7->transcribe-anything)
  Using cached charset_normalizer-3.4.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests->static-ffmpeg>=2.7->transcribe-anything)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting certifi>=2017.4.17 (from requests->static-ffmpeg>=2.7->transcribe-anything)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting SecretStorage>=3.2 (from keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading SecretStorage-3.3.3-py3-none-any.whl.metadata (4.0 kB)
Collecting jeepney>=0.4.2 (from keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading jeepney-0.9.0-py3-none-any.whl.metadata (1.2 kB)
Collecting jaraco.classes (from keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading jaraco.classes-3.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting jaraco.functools (from keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading jaraco.functools-4.1.0-py3-none-any.whl.metadata (2.9 kB)
Collecting jaraco.context (from keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading jaraco.context-6.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting nh3>=0.2.14 (from readme-renderer>=35.0->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading nh3-0.2.21-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting docutils>=0.21.2 (from readme-renderer>=35.0->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Collecting Pygments>=2.5.1 (from readme-renderer>=35.0->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.0.0->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.0.0->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting cryptography>=2.0 (from SecretStorage>=3.2->keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading cryptography-44.0.1-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (5.7 kB)
Collecting more-itertools (from jaraco.classes->keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading more_itertools-10.6.0-py3-none-any.whl.metadata (37 kB)
Collecting cffi>=1.12 (from cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading cffi-1.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine>=6.0.1->uv-iso-env>=1.0.36->transcribe-anything)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Downloading transcribe_anything-3.0.0-py3-none-any.whl (37 kB)
Downloading webvtt_py-0.4.6-py3-none-any.whl (16 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading disklru-2.0.4-py2.py3-none-any.whl (6.5 kB)
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Downloading static_ffmpeg-2.8-py3-none-any.whl (7.1 kB)
Downloading uv_iso_env-1.0.37-py3-none-any.whl (8.7 kB)
Downloading yt_dlp-2025.2.19-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 11.3 MB/s eta 0:00:00
Downloading filelock-3.17.0-py3-none-any.whl (16 kB)
Downloading twine-6.1.0-py3-none-any.whl (40 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading uv-0.6.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.2/16.2 MB 11.4 MB/s eta 0:00:00
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Downloading keyring-25.6.0-py3-none-any.whl (39 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Downloading readme_renderer-44.0-py3-none-any.whl (13 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Downloading rich-13.9.4-py3-none-any.whl (242 kB)
Using cached urllib3-2.3.0-py3-none-any.whl (128 kB)
Downloading id-1.5.0-py3-none-any.whl (13 kB)
Downloading docutils-0.21.2-py3-none-any.whl (587 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.4/587.4 kB 8.0 MB/s eta 0:00:00
Downloading jeepney-0.9.0-py3-none-any.whl (49 kB)
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Downloading nh3-0.2.21-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (739 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.0/739.0 kB 7.7 MB/s eta 0:00:00
Downloading pygments-2.19.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 10.0 MB/s eta 0:00:00
Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Downloading jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
Downloading jaraco.context-6.0.1-py3-none-any.whl (6.8 kB)
Downloading jaraco.functools-4.1.0-py3-none-any.whl (10 kB)
Downloading cryptography-44.0.1-cp39-abi3-manylinux_2_34_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 10.6 MB/s eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading more_itertools-10.6.0-py3-none-any.whl (63 kB)
Downloading cffi-1.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479 kB)
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: docopt, progress
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13749 sha256=5625ea88a20bf8327c02d60901dc7d097f1c6dc77936aa8872ddb030d821fafa
  Stored in directory: /home/user/.cache/pip/wheels/0b/1d/03/175286677fb5a1341cc3e4755bf8ec0ed08f3329afd67446b0
  Building wheel for progress (pyproject.toml) ... done
  Created wheel for progress: filename=progress-1.6-py3-none-any.whl size=9655 sha256=2acdabd57819a76413f5a068fd81dbec5c2282e5f4c5cea45452e04ecd075cb8
  Stored in directory: /home/user/.cache/pip/wheels/50/62/95/d3ee991b65c14c61dfc8e14b2d04eab35b799d9b4243248d65
Successfully built docopt progress
Installing collected packages: progress, docopt, appdirs, yt-dlp, webvtt-py, uv, urllib3, rfc3986, python-dotenv, Pygments, pycparser, packaging, nh3, more-itertools, mdurl, jeepney, jaraco.context, idna, FileLock, docutils, disklru, charset-normalizer, certifi, requests, readme-renderer, markdown-it-py, jaraco.functools, jaraco.classes, cffi, static-ffmpeg, rich, requests-toolbelt, id, cryptography, SecretStorage, keyring, twine, uv-iso-env, transcribe-anything
Successfully installed FileLock-3.17.0 Pygments-2.19.1 SecretStorage-3.3.3 appdirs-1.4.4 certifi-2025.1.31 cffi-1.17.1 charset-normalizer-3.4.1 cryptography-44.0.1 disklru-2.0.4 docopt-0.6.2 docutils-0.21.2 id-1.5.0 idna-3.10 jaraco.classes-3.4.0 jaraco.context-6.0.1 jaraco.functools-4.1.0 jeepney-0.9.0 keyring-25.6.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.6.0 nh3-0.2.21 packaging-24.2 progress-1.6 pycparser-2.22 python-dotenv-1.0.1 readme-renderer-44.0 requests-2.32.3 requests-toolbelt-1.0.0 rfc3986-2.0.0 rich-13.9.4 static-ffmpeg-2.8 transcribe-anything-3.0.0 twine-6.1.0 urllib3-2.3.0 uv-0.6.3 uv-iso-env-1.0.37 webvtt-py-0.4.6 yt-dlp-2025.2.19

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
(.venv) ╭─user@pc ~/d/git 
╰─$  transcribe-anything https://www.youtube.com/watch\?v\=dQw4w9WgXcQ
Purging...
venv_path does not exist.
/home/user/d/git/.venv/lib/python3.13/site-packages/iso_env/api.py:97: UserWarning: Error compiling requirements at /home/user/d/git/.venv/lib/python3.13/site-packages/transcribe_anything/venv/whisper: 1

  × Failed to build `openai-whisper==20240930`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed
      (exit status: 1)

      [stderr]
      <string>:5: DeprecationWarning: pkg_resources is deprecated as an
      API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
          requires = get_requires_for_build({})
        File
      "/home/user/.cache/uv/builds-v0/.tmpriyaVY/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings,
      requirements=[])
      
      ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "/home/user/.cache/uv/builds-v0/.tmpriyaVY/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File
      "/home/user/.cache/uv/builds-v0/.tmpriyaVY/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "/home/user/.cache/uv/builds-v0/.tmpriyaVY/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 21, in <module>
        File "<string>", line 11, in read_version
      KeyError: '__version__'

      hint: This usually indicates a problem with the package or the
      build environment.

  warnings.warn(


```

**Comment by HubKing** [comment]
Oh, wait. I thought it crashed, because it was stuck at `warnings.warn(`, but whilst I was posting the reply above, my CPU's fan began to make a loud noise, and it was working. But probably on CPU, because the CPU usage was high.


```
{
    "cuda_available": false,
    "cuda_devices": [],
    "num_cuda_devices": 0
}
Running transcribe_audio on https://www.youtube.com/watch?v=dQw4w9WgXcQ
Downloading https://github.com/zackees/ffmpeg_bins/raw/main/v5.0/linux.zip -> /home/user/d/git/.venv/lib/python3.13/site-packages/static_ffmpeg/bin/linux.zip
-
............................................................................................................................................................................................................................................................................................................................................................................................................................................
Download of https://github.com/zackees/ffmpeg_bins/raw/main/v5.0/linux.zip -> /home/user/d/git/.venv/lib/python3.13/site-packages/static_ffmpeg/bin/linux.zip completed.
Extracting /home/user/d/git/.venv/lib/python3.13/site-packages/static_ffmpeg/bin/linux.zip -> /home/user/d/git/.venv/lib/python3.13/site-packages/static_ffmpeg/bin
/home/user/d/git/.venv/lib/python3.13/site-packages/transcribe_anything/api.py:169: UserWarning: 

#####################################################################################################################################################
# WARNING: Python version sys.version_info(major=3, minor=13, micro=2, releaselevel='final', serial=0) is not in the range (3, 10, 0) to (3, 11, X).
# transcribe-anything may not work correctly. Please use a supported version of Python.
#####################################################################################################################################################



  warnings.warn(f"{header}\n{msg}\n{footer}\n")
Running:
  yt-dlp --get-title https://www.youtube.com/watch?v=dQw4w9WgXcQ
making dir text_Rick Astley - Never Gonna Give You Up (Official Music Video)
Using temporary directory /tmp/tmpozexk9xz
Running:
  yt-dlp --no-check-certificate https://www.youtube.com/watch?v=dQw4w9WgXcQ -o "out.%(ext)s"
[youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading tv client config
[youtube] dQw4w9WgXcQ: Downloading player 5ae7d525
[youtube] dQw4w9WgXcQ: Downloading tv player API JSON
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[info] dQw4w9WgXcQ: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 39
[download] Destination: out.f616.mp4
[download] 100% of   94.86MiB in 00:00:11 at 8.55MiB/s
[download] Destination: out.f251.webm
[download] 100% of    3.28MiB in 00:00:00 at 9.16MiB/s
[Merger] Merging formats into "out.webm"
Deleting original file out.f251.webm (pass -k to keep)
Deleting original file out.f616.mp4 (pass -k to keep)
Downloaded file:  /tmp/tmpozexk9xz/out.webm
Running:
  static_ffmpeg -y -i /tmp/tmpozexk9xz/out.webm -filter:a speechnorm=e=12.5:r=0.00001:l=1 -acodec pcm_s16le -ar 44100 -ac 1 /tmp/tmp8232i6be.wav
Downloading complete.
WARNING: NOT using GPU acceleration, using 10x slower CPU instead.
Using device cpu
Running whisper on /tmp/tmpxwmgkjbl.wav (will install models on first run)
Running:
  whisper /tmp/tmpxwmgkjbl.wav --device cpu --model small --output_dir /tmp/tmp_qdni1c3 --task transcribe
100%|███████████████████████████████████████| 461M/461M [00:42<00:00, 11.5MiB/s]
/home/user/d/git/.venv/lib/python3.13/site-packages/transcribe_anything/venv/whisper/.venv/lib/python3.10/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
Detected language: English
[00:00.000 --> 00:27.000]  We're no strangers to love, you know the rules and so do I
[00:27.000 --> 00:31.000]  I've built commitments while I'm thinking of
[00:31.000 --> 00:35.000]  You wouldn't get this from any other guy
[00:35.000 --> 00:40.000]  I just wanna tell you how I'm feeling
[00:40.000 --> 00:43.000]  Gotta make you understand
[00:43.000 --> 00:45.000]  Never gonna give you up
[00:45.000 --> 00:47.000]  Never gonna let you down
[00:47.000 --> 00:51.000]  Never gonna run around and desert you
[00:51.000 --> 00:53.000]  Never gonna make you cry
[00:53.000 --> 00:55.000]  Never gonna say goodbye
[00:55.000 --> 00:58.000]  Never gonna tell a lie
[00:58.000 --> 01:00.000]  And hurt you
[01:00.000 --> 01:04.000]  We've known each other for so long
[01:04.000 --> 01:09.000]  Your heart's been aching but you're too shy to say it
[01:09.000 --> 01:13.000]  Inside we both know what's been going on
[01:13.000 --> 01:17.000]  We know the game and we're gonna play it
[01:17.000 --> 01:22.000]  And if you ask me how I'm feeling
[01:22.000 --> 01:25.000]  Don't tell me you're too much to see
[01:25.000 --> 01:27.000]  Never gonna give you up
[01:27.000 --> 01:29.000]  Never gonna let you down
[01:29.000 --> 01:33.000]  Never gonna run around and desert you
[01:33.000 --> 01:35.000]  Never gonna make you cry
[01:35.000 --> 01:38.000]  Never gonna say goodbye
[01:38.000 --> 01:40.000]  Never gonna tell a lie
[01:40.000 --> 01:42.000]  And hurt you
[01:42.000 --> 01:44.000]  Never gonna give you up
[01:44.000 --> 01:46.000]  Never gonna let you down
[01:46.000 --> 01:50.000]  Never gonna run around and desert you
[01:50.000 --> 01:52.000]  Never gonna make you cry
[01:52.000 --> 01:54.000]  Never gonna say goodbye
[01:54.000 --> 01:57.000]  Never gonna tell a lie
[01:57.000 --> 01:59.000]  And hurt you
[02:08.000 --> 02:10.000]  Never gonna give
[02:12.000 --> 02:14.000]  Never gonna give

```

**Comment by Mischala** [comment]
I have an Intel Arc A770.
Running Bazzite (Fedora based immutable distro)
Installed transcribe-anything via pip.

Doesn't seem to detect or use the Intel GPU.
Will do a bit of noodling around and see if I can convince it to see the Intel GPU.
I know Intel does/did publish throw own fork of Torch, might be one avenue of investigation.

@zackees might need to reopen? Can assign to me if you like

**Comment by zackees** [comment]
go for it

**Comment by Mischala** [comment]
[PR Up](https://github.com/zackees/transcribe-anything/pull/127)

Here is the output running on my Intel Arc A770
In a Ubuntu Distrobox container, on top of Bazzite.

```
(venv) 📦[mischa@Transcribe transcribe-anything]$ transcribe-anything --device xpu https://www.youtube.com/watch?v=RXJKdh1KZ0w
Running transcribe_audio on https://www.youtube.com/watch?v=RXJKdh1KZ0w
Running:
  yt-dlp --get-title https://www.youtube.com/watch?v=RXJKdh1KZ0w
making dir text_Rockwell Retro Encabulator
Using temporary directory /tmp/tmpbcno97im
Running:
  yt-dlp --no-check-certificate -x https://www.youtube.com/watch?v=RXJKdh1KZ0w -o "out.%(ext)s"
[youtube] Extracting URL: https://www.youtube.com/watch?v=RXJKdh1KZ0w
[youtube] RXJKdh1KZ0w: Downloading webpage
WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
[youtube] RXJKdh1KZ0w: Downloading android vr player API JSON
[info] RXJKdh1KZ0w: Downloading 1 format(s): 251
[download] Destination: out.webm
[download] 100% of    1.71MiB in 00:00:00 at 4.96MiB/s
[ExtractAudio] Destination: out.opus
Deleting original file out.webm (pass -k to keep)
Downloaded file:  /tmp/tmpbcno97im/out.opus
Running:
  /var/home/mischa/Documents/Dev/transcribe-anything/venv/bin/static_ffmpeg -y -i /tmp/tmpbcno97im/out.opus -filter:a speechnorm=e=12.5:r=0.00001:l=1 -acodec pcm_s16le -ar 16000 -ac 1 /tmp/tmp7oxiil5y.wav
Downloading complete.
#####################################
####### INTEL XPU MODE! #############
#####################################
Using device xpu
Running whisper on /tmp/tmpyogsw975.wav (will install models on first run)
Running:
  python /var/home/mischa/Documents/Dev/transcribe-anything/venv/lib/python3.14/site-packages/transcribe_anything/_xpu_whisper.py --device-id xpu --file-name /tmp/tmpyogsw975.wav --model-name openai/whisper-small --task transcribe --transcript-path /tmp/tmpg_4ynw53/out.json
### HUGGING FACE TOKEN IS NOT ACTIVE - NO SPEAKER JSON GENERATED ###
Done! Files were saved to /var/home/mischa/Documents/Dev/transcribe-anything/text_Rockwell Retro Encabulator
```


And the goods, from the Retro Encabulator video I used to test: 
<details><summary>Test video output</summary>

```json
{
  "text": "Here at Rockwell Automation's World Headquarters, research has been proceeding to develop a line of automation products that establishes new standards for quality, technological leadership, and operating excellence. With customer success as our primary focus, work has been proceeding on the crudely conceived idea of an instrument that would not only provide inverse reactive current for use in unilateral phase detractors, but would also be capable of automatically synchronizing cardinal gram meters. Such an instrument comprised of Dodge gears and bearings, reliant electric motors, Allen-Bradley controls and all monitored by Rockwell Software is Rockwell Automation's Retro-Encabulator. Now basically the only new principle involved is that instead of power being generated by the relative motion of conductors and fluxes, it's produced by the modial interaction of magneto-reluctance and capacitive-directance. The original machine had a base plate of prefamulated amulite surmounted by a malleable logarithmic casing in such a way that the two spurving bearings ran a direct line with a panometric fam. The lineup consisted simply of six hydrocoptic marzol veins, so fitted to the ambifacient lunar wane shaft that side fumbling was effectively prevented. The main winding was of the normal lotus-o-deltoid type placed in panendermic semi-boloid slots of the stator. Every seventh conductor being connected by a non-reversible tremie pipe to the differential girdle spring on the up end of the gram meters. Moreover, whenever fluorescent score motion is required, it may also be employed in conjunction with a drawn reciprocation ding alarm to reduce sinusoidal deplaneration. The retroincabulator has now reached a high level of development, and it's being successfully used in the operation of Milford Trenions. It's available soon, wherever Rockwell Automation products are sold.",
  "chunks": [
    {
      "timestamp": [
        0.0,
        4.0
      ],
      "text": "Here at Rockwell Automation's World Headquarters,"
    },
    {
      "timestamp": [
        4.0,
        107.0
      ],
      "text": "research has been proceeding to develop a line of automation products that establishes new standards for quality, technological leadership, and operating excellence. With customer success as our primary focus, work has been proceeding on the crudely conceived idea of an instrument that would not only provide inverse reactive current for use in unilateral phase detractors, but would also be capable of automatically synchronizing cardinal gram meters. Such an instrument comprised of Dodge gears and bearings, reliant electric motors, Allen-Bradley controls and all monitored by Rockwell Software is Rockwell Automation's Retro-Encabulator. Now basically the only new principle involved is that instead of power being generated by the relative motion of conductors and fluxes, it's produced by the modial interaction of magneto-reluctance and capacitive-directance. The original machine had a base plate of prefamulated amulite surmounted by a malleable logarithmic casing in such a way that the two spurving bearings ran a direct line with a panometric fam. The lineup consisted simply of six hydrocoptic marzol veins, so fitted to the ambifacient lunar wane shaft that side fumbling was effectively prevented. The main winding was of the normal lotus-o-deltoid type placed in panendermic semi-boloid slots of the stator. Every seventh conductor being connected by a non-reversible tremie pipe to the differential girdle spring on the up end of the gram meters. Moreover, whenever fluorescent score motion is required, it may also be employed in conjunction with a drawn reciprocation ding alarm to reduce sinusoidal deplaneration."
    },
    {
      "timestamp": [
        107.0,
        115.0
      ],
      "text": "The retroincabulator has now reached a high level of development, and it's being successfully used in the operation of Milford Trenions."
    },
    {
      "timestamp": [
        115.0,
        120.0
      ],
      "text": "It's available soon, wherever Rockwell Automation products are sold."
    }
  ]
}
```
</details>
